### ISSUE TITLE
No Highlighting in Markdown Files

### ISSUE THREAD

**Issue by W4RH4WK** [GoliafRS/Monokai-GRS#1]
![screenshot_2017-05-26_14-04-28](https://cloud.githubusercontent.com/assets/328798/26493884/4a8f71cc-421c-11e7-9691-ccea2574266e.png)

I really like your theme, yet I seem to run into a problem when editing Markdown files. Almost nothing is highlighted as can be seen in the screenshot above (left). Other filetypes like C (right) work just fine.

**Comment by GoliafRS** [comment]
Added in version 0.2.0.
