### ISSUE TITLE
Issue with Elixir as of 0.2.40

### ISSUE THREAD

**Issue by TheFirstAvenger** [GoliafRS/Monokai-GRS#2]
Given this code in a `.ex` file:
```
defmodule Monokai do
  def render("show.json", %{post: post, conn: conn}) do
    show(post, conn, %{})
  end

  def render("index.json", %{posts: posts, conn: conn, params: params}) do
    index(posts, Plug.Conn.assign(conn, :body, false), params)
  end
end

```

with the ElixirLS extension, I had this on 0.2.38:

<img width="555" alt="Screen Shot 2020-05-21 at 2 18 33 PM" src="https://user-images.githubusercontent.com/8557871/82592130-703d6100-9b6e-11ea-8c3a-2cddd9af2529.png">

on 0.2.40, it became this:

<img width="571" alt="Screen Shot 2020-05-21 at 2 19 38 PM" src="https://user-images.githubusercontent.com/8557871/82592154-792e3280-9b6e-11ea-8970-2603801c7b14.png">

and on the latest, 0.2.50, it became:

<img width="552" alt="Screen Shot 2020-05-21 at 2 20 13 PM" src="https://user-images.githubusercontent.com/8557871/82592178-83e8c780-9b6e-11ea-9ae6-493a3a22ce7d.png">

Both the function name (`render`) and the module name (`Plug.Conn`) are no longer colored as they used to be.

**Comment by GoliafRS** [comment]
@TheFirstAvenger, please check version `0.2.52`.
And then write here the results.

**Comment by TheFirstAvenger** [comment]
Better! Looks like the module attributes (`@attribute`) and specs (`@spec`) also lost their color:
<img width="411" alt="Screen Shot 2020-05-21 at 5 53 11 PM" src="https://user-images.githubusercontent.com/8557871/82610490-7d694880-9b8c-11ea-9960-5391a3de9c70.png">
<img width="403" alt="Screen Shot 2020-05-21 at 5 57 35 PM" src="https://user-images.githubusercontent.com/8557871/82610538-9540cc80-9b8c-11ea-90b9-70e5f2266af7.png">
<img width="298" alt="Screen Shot 2020-05-21 at 5 53 51 PM" src="https://user-images.githubusercontent.com/8557871/82610661-c91bf200-9b8c-11ea-8255-fee173fdcf99.png">
<img width="304" alt="Screen Shot 2020-05-21 at 5 58 39 PM" src="https://user-images.githubusercontent.com/8557871/82610641-bd303000-9b8c-11ea-98b9-d480372625d1.png">

**Comment by GoliafRS** [comment]
@TheFirstAvenger, `0.2.53` version is published, please check.

**Comment by TheFirstAvenger** [comment]
Looks great, thanks!
